/**
 * @file InsightsCard.tsx
 * @description AI insights card component.
 * Displays structured sustainability suggestions generated by the Gemini API.
 * Renders checkboxes for action items, difficulty badges, and potential savings tags.
 */

'use client';

import { useCarbonStore } from '@/store/carbon-store';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '../ui/Card';
import { Button } from '../ui/Button';
import { Sparkles, RefreshCcw, AlertTriangle, Trophy, Brain } from 'lucide-react';
import React from 'react';
import { safeAsync } from '@/lib/errors';

export function InsightsCard() {
  const activities = useCarbonStore((state) => state.activities);
  const user = useCarbonStore((state) => state.user);
  const insights = useCarbonStore((state) => state.insights);
  const isLoading = useCarbonStore((state) => state.isLoading);
  const setInsights = useCarbonStore((state) => state.setInsights);
  const setLoading = useCarbonStore((state) => state.setLoading);

  const fetchInsights = async () => {
    setLoading(true);
    const [data, error] = await safeAsync(
      fetch('/api/insights', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          activities,
          user,
        }),
      }).then(async (r) => {
        if (!r.ok) throw new Error('Failed to generate insights');
        return r.json();
      })
    );

    if (error) {
      console.error('Insights fetch failed:', error.message);
      setLoading(false);
      return;
    }

    if (data && data.insights && Array.isArray(data.insights)) {
      setInsights(data.insights);
    }
    setLoading(false);
  };

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'tip':
        return <Brain className="w-4 h-4 text-emerald-400" />;
      case 'warning':
        return <AlertTriangle className="w-4 h-4 text-rose-400" />;
      case 'achievement':
        return <Trophy className="w-4 h-4 text-yellow-400" />;
      default:
        return <Sparkles className="w-4 h-4 text-sky-400" />;
    }
  };

  const getDifficultyColor = (diff: string) => {
    switch (diff) {
      case 'easy':
        return 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400';
      case 'medium':
        return 'bg-yellow-500/10 border-yellow-500/20 text-yellow-400';
      case 'hard':
        return 'bg-rose-500/10 border-rose-500/20 text-rose-400';
      default:
        return 'bg-slate-500/10 border-slate-550/20 text-slate-400';
    }
  };

  return (
    <Card className="relative overflow-hidden border-emerald-500/20 shadow-emerald-950/5">
      <div className="absolute top-0 right-0 w-[150px] h-[150px] bg-emerald-500/10 rounded-full blur-[80px] pointer-events-none" />

      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle className="text-sm font-semibold text-white flex items-center space-x-2">
            <div className="p-1 bg-emerald-500/20 border border-emerald-500/30 rounded-lg">
              <Sparkles className="w-4 h-4 text-emerald-400" />
            </div>
            <span>Verdant AI Insights</span>
          </CardTitle>
          <CardDescription>AI-powered suggestions to lower your footprint</CardDescription>
        </div>

        <Button
          variant="outline"
          size="sm"
          disabled={isLoading}
          onClick={fetchInsights}
          className="h-8 w-8 p-0 border-slate-800 hover:border-slate-700 bg-slate-900/50"
          id="btn-refresh-insights"
        >
          <RefreshCcw className={`w-3.5 h-3.5 text-slate-400 ${isLoading ? 'animate-spin' : ''}`} />
          <span className="sr-only">Refresh Insights</span>
        </Button>
      </CardHeader>

      <CardContent>
        {isLoading ? (
          <div className="flex flex-col items-center justify-center py-12 space-y-4">
            <div className="relative">
              <div className="w-10 h-10 border-2 border-emerald-500/20 border-t-emerald-400 rounded-full animate-spin" />
              <Sparkles className="w-4 h-4 text-emerald-400 absolute top-3 left-3 animate-pulse" />
            </div>
            <p className="text-xs font-medium text-slate-400 tracking-wide">AI is analyzing your profile...</p>
          </div>
        ) : insights.length === 0 ? (
          <div className="text-center py-8">
            <Brain className="w-8 h-8 text-slate-600 mx-auto mb-2 stroke-[1.5]" />
            <p className="text-xs text-slate-400 font-medium">No insights generated yet</p>
            <p className="text-[10px] text-slate-555 mt-1">Click the refresh icon above to trigger AI recommendations.</p>
          </div>
        ) : (
          <div className="space-y-4 max-h-[380px] overflow-y-auto pr-1 custom-scrollbar">
            {insights.map((insight) => (
              <div
                key={insight.id}
                className="bg-slate-950/40 p-4 rounded-xl border border-slate-900 space-y-3"
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-center space-x-2">
                    <div className="p-1.5 bg-slate-900 border border-slate-800 rounded-lg">
                      {getInsightIcon(insight.type)}
                    </div>
                    <div>
                      <h4 className="text-xs font-bold text-white">{insight.title}</h4>
                      <p className="text-[9px] text-slate-500 capitalize">{insight.category} Insight</p>
                    </div>
                  </div>

                  <div className="flex items-center space-x-1.5">
                    <span className={`text-[8px] font-bold px-1.5 py-0.5 rounded border uppercase ${getDifficultyColor(insight.difficulty)}`}>
                      {insight.difficulty}
                    </span>
                    <span className="text-[9px] font-mono text-emerald-400 bg-emerald-500/5 px-1.5 py-0.5 rounded border border-emerald-500/10">
                      -{insight.potentialSavingKg} kg CO₂
                    </span>
                  </div>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed pl-1">
                  {insight.description}
                </p>

                {insight.actionItems && insight.actionItems.length > 0 && (
                  <div className="pl-1 pt-2 border-t border-slate-900 space-y-1.5">
                    <p className="text-[10px] font-bold text-slate-400">Action Items:</p>
                    {insight.actionItems.map((item, idx) => (
                      <label key={idx} className="flex items-start space-x-2 text-[10px] text-slate-300 hover:text-slate-200 cursor-pointer select-none">
                        <input
                          type="checkbox"
                          className="mt-0.5 rounded border-slate-850 bg-slate-950 text-emerald-500 focus:ring-0 focus:ring-offset-0 h-3 w-3"
                        />
                        <span>{item}</span>
                      </label>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
